# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('custo', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('quantidade', models.IntegerField(default='0')),
                ('reposicao', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='estoque',
            name='Local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Local'),
        ),
    ]
