# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
