# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20160509_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='Local',
            new_name='local',
        ),
    ]
